### ISSUE TITLE
Capstone Project Kanban board

### ISSUE THREAD

**Issue by shahira-sadat** [nimplay/api-webapp#5]
Hi, Thanks for your review
here is the link to our GitHub project:  https://github.com/nimplay/api-webapp/projects/2

We are 2 people in the group: @nimplay  and @shahira-sadat

**Comment by nimplay** [comment]
this is the first pull request.
https://github.com/nimplay/api-webapp/pull/6

**Comment by Gambit142** [comment]
Hi Team 👋, 

Good job attempting to set up your Kanban board. 

## Required Changes ♻️
_Although you provided us with a link to the Kanban board, the link is broken and shows this error page:_

![image](https://user-images.githubusercontent.com/77106962/180870227-d1a167d4-7104-4de8-b96e-76d8479e73fa.png)

#### Hint: Kindly follow the steps described in this [article](https://github.com/microverseinc/curriculum-tools-copy-projects) to set up your Kanban board 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by BenMukebo** [comment]
### Hi @nimplay, @shahira-sadat, 👋🏻 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] According to the project requirement, the Students' board should be a copy of [this template board](https://github.com/microverseinc/curriculum-javascript/projects/1). Kindly address this and make sure For a team with **two** people:
  - [ ] If all cards with the `Student C` suffix on the template were removed from your ' copy of the template. **Number of cards on board should be equal to 15.
  - [ ] Cards are assigned to team members in a fair way and for that, you need to decide who is `Student A`, `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
  - [ ]  All cards with `group task` in the title are assigned to someone (it does not matter to whom as students had freedom with that).

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @nimplay, and @shahira-sadat👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
